spring:
  application:
    name: spring-actuator-test
  cloud:
    gateway:
      metrics:
        enabled: true
      routes:
      -
        id: test-service
        uri: https://www.httpstat.us
        predicates:
        - Path=/test-service/**
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'
    export:
      prometheus:
        enabled: true
